"""add_share_link_created_by

Revision ID: d48a0b63f867
Revises: edd5e167ee43
Create Date: 2026-02-05 20:12:49.100397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd48a0b63f867'
down_revision: Union[str, None] = 'edd5e167ee43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_links', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.alter_column('share_links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'share_links', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_links', type_='foreignkey')
    op.alter_column('share_links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('share_links', 'created_by')
    # ### end Alembic commands ###
